### ISSUE TITLE
Get/SetGlobalInt

### ISSUE THREAD

**Issue by iD4NG3R** [Mr-Gash/GMod-Deathrun#10]
Since the update of 03.09.15 Get/SetGlobalVar have been removed, thus breaking the gamemode on any server that has been updated.

**Comment by Mr-Gash** [comment]
```lua
> print( GetGlobalInt )...
function: 0x12b8dea8
```

Get/SetGlobalVar were removed, however, Var literally means Var. It doesn't mean every Get/SetGlobal* function. Nothing should be broken - even went to test it, works for me.
