### ISSUE TITLE
Timer, mapvote, and auto jump broken

### ISSUE THREAD

**Issue by SexyWalrus** [Mr-Gash/GMod-Deathrun#12]
Ever since the gmod update the deathrun game modes autojump has not been working neither has the mapvoting and the timer on the top of the screen

**Comment by Mr-Gash** [comment]
Works fine for me.

**Comment by Sklambo** [comment]
Yeah Im having the same problem, When pressing F1 the where I could once enable and disable autojump there is a red box saying "Autojump (disallowed)"

**Comment by Mr-Gash** [comment]
That means the server has disabled autojump.

**Comment by Sklambo** [comment]
And where would I go if I wanted to enable it, believe me I have looked.

**Comment by Sklambo** [comment]
Just for some background I have not even gone into the deathrun gamemode folder and the bhop was fine until the Gmod update.

local highlight = CreateConVar( "dr_highlight_admins", "1", FCVAR_ARCHIVE )
local rounds = CreateConVar( "dr_total_rounds", "10", FCVAR_ARCHIVE )
local suicide = CreateConVar( "dr_allow_death_suicide", "0", FCVAR_ARCHIVE )
local bhop = CreateConVar( "dr_allow_autojump", "1", FCVAR_ARCHIVE )
local uammo = CreateConVar( "dr_unlimited_ammo", "1", FCVAR_ARCHIVE )
local pickup = CreateConVar( "dr_allow_death_pickup", "0", FCVAR_ARCHIVE )
local falldamage = CreateConVar( "dr_realistic_fall_damage", "1", FCVAR_ARCHIVE )
local push = CreateConVar( "dr_push_collide", "0", FCVAR_ARCHIVE )
