### ISSUE TITLE
dr_save_weapons not working

### ISSUE THREAD

**Issue by Dogeyy** [Mr-Gash/GMod-Deathrun#13]
when I try do dr_save_weapon it gives me an error in the sv_weps file at line 70, saying 'IsSuperAdmin' is a nil value, any fix for this?

**Comment by Dogeyy** [comment]
Is there no fix for this?

**Comment by Mr-Gash** [comment]
It means you're calling it from the server console, not your own console. The way it works is by getting the weapon you're looking at - the server isn't a player and can't be looking at an entity, can it?

**Comment by Dogeyy** [comment]
It indeed can not, but trying it in a local game with the ULX and ULIB addon doesn't work either, I still get the same error, and when replacing the IsSuperAdmin with if ply:IsUserGroup("superadmin") doesn't really work either, unless I'm doing something wrong, which I find highly impossible.

Notify me if you need my sv_weps file and see how it looks like, on how I tryed to fix it.

**Comment by Mr-Gash** [comment]
If you modified the gamemode, redownload and try a clean version. If it's erroring on a clean version, remove your addons and re-add them one-by-one until the error comes up. I can't replicate the issue, so it's probably something you've added. If you're using ULX for whatever reason to run the command (like "ulx rcon dr_save_weapon" or something like that) - don't. Just run the command normally in your own console and it should work.

**Comment by Dogeyy** [comment]
I only have ULX and ULib, I even reinstalled my GMod, but I keep getting this error...
