### ISSUE TITLE
Setting the player model of a Death

### ISSUE THREAD

**Issue by chudders1231** [Mr-Gash/GMod-Deathrun#36]
What is the hook to set the Death's Player model!?

Thanks,
Chad

**Comment by Mr-Gash** [comment]
[ChangePlayerModel](https://github.com/Mr-Gash/GMod-Deathrun/blob/master/deathrun/hook_examples.lua#L24)

Just check if the player's team matches TEAM_DEATH.

**Comment by chudders1231** [comment]
But is it ply:isTeamDeath or is it ply:isTeam_Death. or is it something else?
Sorry i am new to lua and i am not sure about what to call.

Thanks
Chad

**Comment by Mr-Gash** [comment]
``` Lua
hook.Add("ChangePlayerModel", "a", function( ply )
    if ply:Team() == TEAM_DEATH then
        return "thing"
    end
end)
```

**Comment by chudders1231** [comment]
Thanks man. Can i also set the weapon in that? or would i need to create a hook like ChangeWeaponModel or something.

**Comment by Mr-Gash** [comment]
There's no hook to modify the weapon loadout (at least, none provided by Deathrun). Since I'm pretty sure the gamemode function of a hook runs before any added with hook.Add, the easiest way would probably be:

``` Lua
hook.Add( "Initialize", "Overwrite Gamemode Loadout", function() -- This is called after the GM loads.
    function GAMEMODE:PlayerLoadout( ply ) -- Now that the gamemode has loaded, overwrite the default loadout method.
        if ply:Team() == TEAM_DEATH then
            ply:Give( "something" )
        else
            ply:Give( "weapon_crowbar" )
        end
    end
end )
```

The function defined by Deathrun simply gives a crowbar.

**Comment by chudders1231** [comment]
Sorry for this being a pain. And i know your nothing to do with pointshop but i appreciate your help if you can offer it. 

When giving a weapon via pointshop, how do i stop the person from dropping it. E.G They buy a sword and then they can press q to drop it.

Also, when they have a weapon from the pointshop, why do they have the crossbar as-well.? I have called the "strip weapon" thing. What else could i do to stop it?

Thanks!
Chad Masters

**Comment by Mr-Gash** [comment]
You'll have to modify [this section of code](https://github.com/Mr-Gash/GMod-Deathrun/blob/2838ad6a4ba05116c268c8b8d1b9bd6389f9527d/deathrun/gamemode/init.lua#L289-L299) for stopping players from dropping weapons. If you're stripping weapons before giving a new one, yet they still have a crowbar, that means the hook you're handling it in is called before PLayerLoadout.

**Comment by chudders1231** [comment]
Ok, so taking from what you said, i got it to remove the crowbar on equip / buy. However it still gives the crowbar back on round start. Is there a deathrun hook for this?

Thanks,
Chad

**Comment by Mr-Gash** [comment]
I'm assuming you're handling the giving/stripping of weapons in PlayerSpawn. Change that to PlayerLoadout.

**Comment by chudders1231** [comment]
I shall try that thanks!

Thanks,
Chad
